"""Render the quality report as one self-contained HTML page plus a machine-readable JSON file."""

from __future__ import annotations

import html
import json

import pandas as pd

CSS = """
body { font: 14px/1.5 "Helvetica Neue", Arial, sans-serif; color: #16212b; max-width: 1080px; margin: 0 auto;
       padding: 24px 16px; background: #fff; }
h1 { font-size: 24px; margin: 0 0 4px; } h2 { font-size: 17px; margin: 28px 0 8px; color: #1f5f8b; }
.sub { color: #52514e; margin: 0 0 16px; }
.tiles { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 12px; }
.tile { background: #f4f6f8; border-radius: 8px; padding: 12px 14px; }
.tile .v { font-size: 22px; font-weight: 700; } .tile .l { color: #52514e; font-size: 12px; }
table { border-collapse: collapse; width: 100%; font-size: 13px; margin: 6px 0; }
th, td { text-align: left; padding: 5px 8px; border-bottom: 1px solid #e4e3df; vertical-align: top; }
th { color: #52514e; font-weight: 600; } th.n, td.n { text-align: right; font-variant-numeric: tabular-nums; }
.sev { font-size: 11px; font-weight: 700; padding: 2px 6px; border-radius: 10px; }
.error { background: #fbe0dc; color: #8f2013; } .warning { background: #fdf1d6; color: #7a5300; }
.info { background: #e3eef7; color: #1f5f8b; } .ok { color: #1f6f5c; font-weight: 600; }
.note { color: #52514e; font-size: 12.5px; } code { background: #f4f6f8; padding: 1px 4px; border-radius: 3px; }
.scroll { overflow-x: auto; } table.wide { min-width: 820px; }
@media print { body { max-width: none; padding: 0; font-size: 11px; } table { font-size: 10px; }
  table.wide { min-width: 0; } .scroll { overflow: visible; } h2 { break-after: avoid; } tr { break-inside: avoid; }
  .tile .v { font-size: 18px; } a { color: inherit; } }
@media (max-width: 600px) { table { font-size: 12px; } th, td { padding: 4px; } }
"""


LABELS: dict[str, str] = {}  # filled from the contract's report.labels


def _label(field: str) -> str:
    return LABELS.get(field, field.replace("_", " "))


def _fmt(n) -> str:
    return f"{int(n):,}"


def _pct(x: float, d: int = 2) -> str:
    if 0 < x < 10**-d / 100:
        return f"<{10**-d:.{d}f}%"
    return f"{100 * x:.{d}f}%"


def _styles(items: list[str]) -> str:
    """'file.csv: quoted, CamelCase' entries -> one line per distinct style with its file count."""
    counts: dict[str, int] = {}
    for i in items:
        style = i.split(": ", 1)[1]
        counts[style] = counts.get(style, 0) + 1
    return "<br>".join(f"{html.escape(k)} ({n} file{'s' if n > 1 else ''})" for k, n in counts.items())


def table(df: pd.DataFrame, cols: dict, num: set | None = None, raw: set | None = None, cls: str = "") -> str:
    """Columns in `raw` already hold HTML (built from escaped parts); every other value is escaped here."""
    num, raw = num or set(), raw or set()
    head = "".join(f"<th{' class=n' if c in num else ''}>{html.escape(lab)}</th>" for c, lab in cols.items())
    body = []
    for _, r in df.iterrows():
        cells = []
        for c in cols:
            v = r[c]
            text = str(v) if c in raw else html.escape(str(v))
            cells.append(f"<td{' class=n' if c in num else ''}>{text}</td>")
        body.append("<tr>" + "".join(cells) + "</tr>")
    return f"<div class='scroll'><table class='{cls}'><tr>{head}</tr>{''.join(body)}</table></div>"


def render(result: dict, path_html, path_json) -> None:
    with open(path_json, "w") as f:
        json.dump(result, f, indent=2, default=str, allow_nan=False)
    cfg = result.get("report", {})
    LABELS.clear()
    LABELS.update(cfg.get("labels", {}))
    ent, ent1 = cfg.get("entity", "records"), cfg.get("entity_singular", "record")
    cur, prev = result["current"], result.get("previous")
    s = cur["split"]
    tiles = [
        ("Rows checked", _fmt(s["rows"])),
        ("In clean table (no errors)", _fmt(s["clean"])),
        ("Quarantined (errors)", _fmt(s["quarantined"])),
        ("Flagged (warnings)", _fmt(s["flagged"])),
        ("Rules", str(len(cur["rules"]))),
    ]
    parts = [
        f"<h1>{html.escape(cfg.get('title', 'Data quality report'))}: {html.escape(result['dataset'])}</h1>",
        f"<p class='sub'>Snapshot as of {html.escape(cur['as_of'])}"
        + (f", compared with {html.escape(prev['as_of'])}" if prev else "")
        + ". Generated by "
        + (
            f"<a href='{html.escape(cfg['source_link'])}'>the data-quality pipeline</a>."
            if cfg.get("source_link")
            else "the data-quality pipeline."
        )
        + f" {html.escape(cfg.get('privacy_note', ''))}</p>",
        "<div class='tiles'>"
        + "".join(f"<div class='tile'><div class='v'>{v}</div><div class='l'>{lab}</div></div>" for lab, v in tiles)
        + "</div>",
    ]

    # Schema and format drift
    if prev:
        sd = result["schema_drift"]
        rows = [
            (
                "Header style",
                _styles(prev["schema"]["header_style"]),
                _styles(cur["schema"]["header_style"]),
            ),
            (
                "Columns not in the contract",
                html.escape(", ".join(prev["schema"]["unexpected"]) or "none"),
                html.escape(", ".join(cur["schema"]["unexpected"]) or "none"),
            ),
            (
                "Contract columns missing",
                html.escape(
                    ", ".join(prev["schema"]["missing_optional"] + prev["schema"]["missing_required"]) or "none"
                ),
                html.escape(", ".join(cur["schema"]["missing_optional"] + cur["schema"]["missing_required"]) or "none"),
            ),
        ]
        for k in sorted(set(prev["normalizations"]) | set(cur["normalizations"])):
            rows.append(
                (
                    k.replace("__", ": ")
                    .replace("_", " ")
                    .replace("us date", "US date")
                    .replace("true false", "TRUE/FALSE"),
                    _fmt(prev["normalizations"].get(k, 0)),
                    _fmt(cur["normalizations"].get(k, 0)),
                )
            )
        df = pd.DataFrame(rows, columns=["item", "prev", "cur"])
        parts += [
            "<h2>1. Schema and format drift between snapshots</h2>",
            "<p class='note'>The publisher changed the file format between quarters. The contract maps both "
            "formats to one schema; each fix applied is counted.</p>",
            table(df, {"item": "Item", "prev": prev["as_of"], "cur": cur["as_of"]}, raw={"prev", "cur"}),
            f"<p class='note'>Columns whose share of missing values changed by more than 1 point: "
            f"{html.escape(sd['null_rate_shifts']) or 'none'}.</p>",
        ]

    # Rule results
    r = pd.DataFrame(cur["rules"])
    r["sev"] = [f"<span class='sev {html.escape(v)}'>{html.escape(v)}</span>" for v in r["severity"]]
    r["failed_f"] = [(_fmt(v) if v else "<span class='ok'>0</span>") for v in r["failed"]]
    r["rate"] = [html.escape(_pct(v, 3)) for v in r["fail_rate"]]
    r["example"] = r["example"].fillna("")
    r["check"] = r["check"].str.replace("_", " ")
    parts += [
        f"<h2>{'2' if prev else '1'}. Validation rules on the {html.escape(cur['as_of'])} snapshot</h2>",
        "<p class='note'>Errors keep a row out of the clean table (it goes to quarantine with the rule ids); "
        "warnings keep the row and flag it; info rules count known features of the source.</p>",
        table(
            r,
            {
                "rule_id": "Rule",
                "sev": "Severity",
                "check": "Check",
                "description": "Description",
                "failed_f": "Rows failing",
                "rate": "Rate",
                "example": "Example (non-personal fields)",
            },
            {"failed_f", "rate"},
            raw={"sev", "failed_f", "rate"},
            cls="wide",
        ),
    ]

    # Snapshot changes
    if prev:
        d = result["diff"]
        mt = d["matching"]
        rows = [
            ("Rows", _fmt(d["rows"]["previous"]), _fmt(d["rows"]["current"])),
            (f"Matched to the same {ent1} in both", _fmt(mt["matched"]), ""),
            ("Only in the earlier snapshot", _fmt(mt["only_previous"]), ""),
            (f"Only in the later snapshot (new {ent})", "", _fmt(mt["only_current"])),
            (
                f"Key shared by several {ent} (not trackable)",
                _fmt(mt["ambiguous_previous"]),
                _fmt(mt["ambiguous_current"]),
            ),
        ]
        parts += [
            "<h2>3. What changed between snapshots</h2>",
            f"<p class='note'>{ent.capitalize()} are matched on "
            f"{html.escape(cfg.get('match_description', 'the contract key'))}. No personal data is used.</p>",
            table(
                pd.DataFrame(rows, columns=["a", "b", "c"]),
                {"a": "", "b": prev["as_of"], "c": cur["as_of"]},
                {"b", "c"},
            ),
        ]
        if "changed_fields" in d:
            ch = pd.DataFrame([{"field": _label(k), "n": _fmt(v)} for k, v in d["changed_fields"].items()])
            parts += [
                f"<p>Matched {ent} whose field changed between the two snapshots. "
                f"{html.escape(cfg.get('expected_change', ''))} (Key fields cannot appear here: a {ent1} whose key "
                "field changed fails to match and is counted in the rows above.)</p>",
                table(ch, {"field": "Field", "n": f"{ent.capitalize()} changed"}, {"n"}),
            ]
        if "resolved_reopened" in d and cfg.get("reopen_note"):
            parts.append(f"<p><b>{_fmt(d['resolved_reopened'])}</b> {html.escape(cfg['reopen_note'])}</p>")
        if "probable_key_revisions" in d:
            pk = d["probable_key_revisions"]
            changed = ", ".join(f"{_label(k)}: {_fmt(v)}" for k, v in pk["changed"].items() if v)
            parts.append(
                f"<p><b>{_fmt(pk['records'])}</b> of the new {ent} match a removed {ent1} on "
                f"{html.escape(', '.join(_label(f) for f in pk['loose_key']))}: probably the same {ent1} with "
                f"a revised key field ({html.escape(changed) or 'none'}). They are counted, not merged.</p>"
            )
        tr = pd.DataFrame(d.get("status_transitions", [])).head(8)
        if len(tr):
            tr["n"] = tr["n"].map(_fmt)
            parts += [
                "<p>Most common status changes:</p>",
                table(tr, {"previous": "From", "current": "To", "n": ent.capitalize()}, {"n"}),
            ]
    parts += [
        "<h2>Notes</h2>",
        "".join(f"<p class='note'>{html.escape(n)}</p>" for n in result.get("notes", [])),
    ]
    page = (
        f"<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' "
        f"content='width=device-width, initial-scale=1'>"
        f"<title>{html.escape(cfg.get('title', 'Data Quality Report'))}</title>"
        f"<style>{CSS}</style></head><body>{''.join(parts)}</body></html>"
    )
    with open(path_html, "w") as f:
        f.write(page)
